name: Boost Scanner
on:
  workflow_dispatch:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master
    types:
      - opened
      - synchronize
jobs:
  scanner:
    name: boost
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
#      - name: Execute trivy-bom-dev
#        uses: boostsecurityio/boostsec-scanner-github@v4
#        with:
#          registry_module: boostsecurityio/trivy-sbom
#          api_token: ${{ secrets.BOOST_API_DEV_TOKEN }}
#          api_endpoint: https://api.dev.boostsec.io
#      - name: Execute trivy-bom-prod
#        uses: boostsecurityio/boostsec-scanner-github@v4
#        with:
#          registry_module: boostsecurityio/trivy-sbom
#          api_token: ${{ secrets.BOOST_API_PROD_TOKEN }}
#      - name: Semgrep with Node.JS
#        uses: boostsecurityio/boostsec-scanner-github@v4
#        env:
#          SEMGREP_RULES: p/nodejsscan p/typescript
#        with:
#          api_token: ${{ secrets.BOOST_API_PROD_TOKEN }}
#          registry_module: boostsecurityio/semgrep
#      - name: CodeQL
#        uses: boostsecurityio/boostsec-scanner-github@v4
#        env:
#          CODEQL_LANGUAGE: javascript
#        with:
#          api_token: ${{ secrets.BOOST_API_DEV_TOKEN }}
#          api_endpoint: https://api.dev.boostsec.io
#          registry_module: boostsecurityio/codeql
#      - name: npm-audit
#        uses: boostsecurityio/boostsec-scanner-github@v4
#        with:
#          api_token: ${{ secrets.BOOST_API_DEV_TOKEN }}
#          api_endpoint: https://api.dev.boostsec.io
#          registry_module: boostsecurityio/npm-audit
#          additional_args: --registry https://github.com/boostsecurityio/scanner-testing.git#main
      - name: npm-audit dev
        uses: boostsecurityio/boostsec-scanner-github@v4
        if: github.event_name != 'pull_request'
        with:
          api_token: ${{ secrets.BOOST_API_DEV_TOKEN }}
          registry_module: boostsecurityio/npm-audit
          api_endpoint: https://api.dev.boostsec.io
